#!/usr/bin/env bash
NUM_FOREGROUND_PROCESSES="$1"
NUM_BACKGROUND_PROCESSES="$2"

(time ./run-fibonacci.sh "$NUM_FOREGROUND_PROCESSES" 1 0) > "foreground_$NUM_FOREGROUND_PROCESSES_$NUM_BACKGROUND_PROCESSES.txt" 2>&1 &
(time ./run-fibonacci.sh "$NUM_BACKGROUND_PROCESSES" 1 19) > "background_$NUM_FOREGROUND_PROCESSES_$NUM_BACKGROUND_PROCESSES.txt" 2>&1 &
wait